name: 'PermRepo — Mūžīgs Arweave Backups'
description: 'Inkrementāls Git repo backups uz Arweave visām CI platformām'
author: 'PermRepo'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  wallet_address:
    description: 'Tava maka publiskā adrese'
    required: true
  subscription_address:
    description: 'Subscription līguma adrese'
    required: false
    default: '0x29f1ed42C6C2E157B7571f9585a9C9Dd6fBcda51'
  nft_address:
    description: 'NFT līguma adrese'
    required: false
    default: '0xeD3eB455cAeb057a034d7bE2368cdCEA37Faa1d4'
  registry_address:
    description: 'Registry līguma adrese'
    required: false
    default: '0x2a5a7F926046BB1A011D9082aB70BF38bfcb9dc9'
  rpc_url:
    description: 'Base RPC URL'
    required: false
    default: 'https://sepolia.base.org'
  turbo_upload_url:
    description: 'Turbo Upload URL'
    required: false
    default: 'https://upload.services.ar-io.dev'
  turbo_payment_url:
    description: 'Turbo Payment URL'
    required: false
    default: 'https://payment.services.ar-io.dev'
outputs:
  status:
    description: 'Backupa statuss'
runs:
  using: 'node20'
  main: 'src/index.js'
